//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu13
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Dfsf1.
    /// </summary>
    //  *** Start programmer edit section *** (dfsf1 CustomAttributes)

    //  *** End programmer edit section *** (dfsf1 CustomAttributes)
    [AutoAltered()]
    [Caption("Dfsf1")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("dfsf1E", new string[0])]
    [View("dfsf1L", new string[0])]
    public class dfsf1 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (dfsf1 CustomMembers)

        //  *** End programmer edit section *** (dfsf1 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "dfsf1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View dfsf1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("dfsf1E", typeof(IIS.mu13.dfsf1));
                }
            }
            
            /// <summary>
            /// "dfsf1L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View dfsf1L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("dfsf1L", typeof(IIS.mu13.dfsf1));
                }
            }
        }
    }
}
